name: Terraform Deploy

on:
  push:
    branches:
      - dev
    paths: 
      - "infra/main/**"

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
          
      - name: Terraform Init
        working-directory: infra/main
        run: terraform init

      - name: Terraform Plan
        working-directory: infra/main
        id: plan
        run: terraform plan -out=tfplan
        continue-on-error: true

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/main/tfplan

      - name: Display Terraform Plan Output
        run: cat infra/main/tfplan

      - name: Request Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.APPROVAL_TOKEN }}
          approvers: saJeremyQin
          minimum-approvals: 1
          issue-title: "Manual approval required for Terraform Apply"
          issue-body: |
            Please review the Terraform plan output uploaded as an artifact.
            Approve to proceed with `terraform apply`.

      - name: Terraform Apply
        if: success()
        working-directory: infra/main
        run: terraform apply -auto-approve tfplan
