name: Terraform Deploy

on:
  push:
    branches:
      - dev
    paths:
      - "infra/main/**"

permissions:
  issues: write       # 给 manual-approval 用
  contents: read      # checkout 和其他步骤需要
  actions: read       # workflow 本身执行需要

jobs:
  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        working-directory: infra/main
        run: terraform init

      - name: Terraform Plan (binary output)
        working-directory: infra/main
        run: terraform plan -out=tfplan

      - name: Terraform Plan (text output)
        working-directory: infra/main
        run: terraform plan

      - name: Upload tfplan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: infra/main/tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan  # 必须等待 plan job 成功
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download tfplan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infra/main

      - name: Request Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ secrets.APPROVAL_TOKEN }}
          approvers: saJeremyQin
          minimum-approvals: 1
          issue-title: "Terraform Apply Approval Needed"
          issue-body: |
            Terraform Plan has been completed and uploaded.
            Review the plan log and approve to apply changes.

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Terraform Init
        working-directory: infra/main
        run: terraform init

      - name: Terraform Apply
        if: success()
        working-directory: infra/main
        run: terraform apply -auto-approve tfplan
