name: Terraform Apply (Manual)

on:
  workflow_dispatch:  # trigger manually

jobs:
  apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Download tfplan artifacts
        uses: actions/download-artifact@v4
        with:
            name: tfplan
            path: infra/main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
          
      - name: Terraform Init
        working-directory: infra/main
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/main
        run: terraform apply tfplan.out
